# Generated by Django 4.2.23 on 2025-07-24 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Technologies',
            new_name='technologies',
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AlterField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 24, 3, 29, 19, 859130), null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='projects.category'),
        ),
    ]
