# Generated by Django 4.2.23 on 2025-07-24 01:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_technologies_project_technologies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AlterField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 24, 3, 37, 1, 354352), null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.category'),
        ),
    ]
