# Generated by Django 4.2.23 on 2025-07-12 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['posted']},
        ),
        migrations.AddField(
            model_name='message',
            name='posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 12, 3, 5, 51, 383538), null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
