# Generated by Django 4.2.23 on 2025-07-12 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_message_options_message_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 12, 17, 33, 19, 771428), null=True),
        ),
    ]
