# Generated by Django 4.2.23 on 2025-07-22 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_message_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 22, 20, 1, 57, 654520), null=True),
        ),
    ]
