# Generated by Django 4.2.23 on 2025-07-24 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_message_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 24, 3, 37, 1, 287799), null=True),
        ),
    ]
